const mongoose = require("mongoose");

const rccfycoSchema = new mongoose.Schema({

  folioConsulta: { type: String, required: true },
  folioConsultaOtorgante: { type: String, required: true },
  claveOtorgante: { type: String, required: true },
  client_id: { type: mongoose.Schema.Types.ObjectId, ref: "Client", required: true },
  persona: {
    apellidoPaterno: { type: String, required: true },
    apellidoMaterno: { type: String, required: true },
    nombres: { type: String, required: true },
    fechaNacimiento: { type: String, required: true },
    RFC: { type: String, required: true },
    nacionalidad: { type: String, required: true },
    residencia: { type: Number, required: true },
    estadoCivil: { type: String, required: true },
    sexo: { type: String, required: true },
    numeroDependientes: { type: String, required: false },
  },
  consultas: [
    {
      fechaConsulta: { type: String, required: false },
      nombreOtorgante: { type: String, required: false },
      telefonoOtorgante: { type: String, required: false },
      tipoCredito: { type: String, required: false },
      claveUnidadMonetaria: { type: String, required: false },
      importeCredito: { type: String, required: false },
    },
  ],
  creditos: [
    {
      fechaActualizacion: { type: String, required: false },
      registroImpugnado: { type: String, required: false },
      nombreOtorgante: { type: String, required: false },
      cuentaActual: { type: String, required: false },
      tipoResponsabilidad: { type: String, required: false },
      tipoCuenta: { type: String, required: false },
      tipoCredito: { type: String, required: false },
      claveUnidadMonetaria: { type: String, required: false },
      valorActivoValuacion: { type: String, required: false },
      numeroPagos: { type: String, required: false },
      frecuenciaPagos: { type: String, required: false },
      montoPagar: { type: String, required: false },
      fechaAperturaCuenta: { type: String, required: false },
      fechaUltimoPago: { type: String, required: false },
      fechaUltimaCompra: { type: String, required: false },
      fechaReporte: { type: String, required: false },
      creditoMaximo: { type: String, required: false },
      saldoActual: { type: String, required: false },
      limiteCredito: { type: String, required: false },
      saldoVencido: { type: String, required: false },
      numeroPagosVencidos: { type: String, required: false },
      pagoActual: { type: String, required: false },
      historicoPagos: { type: String, required: false },
      totalPagosReportados: { type: String, required: false },
      peorAtraso: { type: String, required: false },
      fechaPeorAtraso: { type: String, required: false },
      saldoVencidoPeorAtraso: { type: String, required: false },
    },
  ],
  domicilios: [
    {
      direccion: { type: String, required: false },
      coloniaPoblacion: { type: String, required: false },
      delegacionMunicipio: { type: String, required: false },
      ciudad: { type: String, required: false },
      estado: { type: String, required: false },
      CP: { type: String, required: false },
      fechaResidencia: { type: String, required: false },
      fechaRegistroDomicilio: { type: String, required: false },
    },
  ],
  empleos: [
    {
      nombreEmpresa: { type: String, required: false },
      direccion: { type: String, required: false },
      coloniaPoblacion: { type: String, required: false },
      delegacionMunicipio: { type: String, required: false },
      ciudad: { type: String, required: false },
      estado: { type: String, required: false },
      CP: { type: String, required: false },
      numeroTelefono: { type: String, required: false },
      extension: { type: String, required: false },
      fax: { type: String, required: false },
      puesto: { type: String, required: false },
      fechaContratacion: { type: String, required: false },
      claveMoneda: { type: String, required: false },
      salarioMensual: { type: Number, required: false },
      fechaUltimoDiaEmpleo: { type: String, required: false },
      fechaVerificacionEmpleo: { type: String, required: false },
    },
  ],
  scores: [
    {
      nombreScore: { type: String, required: false },
      valor: { type: Number, required: false },
      razones: [],
    },
  ],
  mensajes: [
    {
      tipoMensaje: { type: String, required: true },
      leyenda: { type: String, required: true },
    },
  ],
},
{ timestamps: true });

const Rccfyco = mongoose.model("Rccfyco", rccfycoSchema);
module.exports = Rccfyco;
